# Generated by Django 6.0.3 on 2026-04-04 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ecommerce_retail', 'E-commerce & Retail'), ('local_business', 'Local Business'), ('education_coaching', 'Education & Coaching'), ('software_tech', 'Software & Tech'), ('creator_brand', 'Creator & Solopreneur'), ('other_custom', 'Other / Custom')], max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=255, null=True)),
                ('tone_of_voice', models.TextField(blank=True, null=True)),
                ('primary_colors', models.JSONField(blank=True, default=list)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('dynamic_fields', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspace_workspace',
            },
        ),
    ]
