# Generated by Django 6.0.3 on 2026-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='brand_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
