# Generated by Django 5.0.3 on 2026-04-17 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('background_url', models.URLField(help_text='URL of the base/generated image', max_length=2048)),
                ('canvas_width', models.PositiveIntegerField(default=1080)),
                ('canvas_height', models.PositiveIntegerField(default=1080)),
                ('elements_json', models.JSONField(blank=True, default=list, help_text='Ordered list of element objects')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='outputs/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='outputs/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'db_table': 'content_editor_studio_designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=128)),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('shape', 'Shape'), ('image', 'Image')], max_length=16)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=100)),
                ('rotation', models.FloatField(default=0)),
                ('z_index', models.IntegerField(default=0)),
                ('style_json', models.JSONField(blank=True, default=dict)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='content_editor_studio.design')),
            ],
            options={
                'db_table': 'content_editor_studio_elements',
                'ordering': ['z_index'],
                'unique_together': {('design', 'element_id')},
            },
        ),
    ]
